language: ruby

cache: bundler

services:
  - mongodb

rvm:
  - 2.3.1

before_install:
  - "gem install rubocop"
  - "rubocop"
  
install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
